"""modify password column

Revision ID: 7e8bef306a9d
Revises: e3d80de4bc09
Create Date: 2025-07-04 23:14:39.865105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# (!) Developer custom imports
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e8bef306a9d'
down_revision: Union[str, Sequence[str], None] = 'e3d80de4bc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
